$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
type: command
name: train_model
display_name: train_model

inputs: 
  train_data:
    type: uri_folder
  test_data:
    type: uri_folder
  n_estimators:
    type: integer
    default: 100
  max_depth:
    type: integer
    default: 5

outputs:
  model_output:
    type: mlflow_model

code: ../../../data-science/src
command: >-
  python train.py 
  --train_data ${{inputs.train_data}}
  --test_data ${{inputs.test_data}}
  --n_estimators ${{inputs.n_estimators}}
  --max_depth ${{inputs.max_depth}}
  --model_output ${{outputs.model_output}}
environment: azureml:used-cars-train-env@latest
