name: sklearn-env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip=21.2.4
  - scikit-learn=0.23.2
  - scipy=1.7.1
  - pip:
      - mlflow==2.8.1
      - azureml-mlflow==1.51.0
      - azureml-inference-server-http
      - azureml-core==1.49.0
      - cloudpickle==1.6.0
